// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitializeUserService() *UserService {
	userRepository := NewUserRepository()
	userService := NewUserService(userRepository)
	return userService
}

// wire.go:

func NewUserRepository() UserRepository {
	return &InMemoryUserRepository{}
}

func NewUserService(repo UserRepository) *UserService {
	return &UserService{repo: repo}
}

var UserSet = wire.NewSet(
	NewUserRepository,
	NewUserService,
)
